// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AgeCategory struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	MinAge       pgtype.Int4        `json:"min_age"`
	MaxAge       pgtype.Int4        `json:"max_age"`
	DisplayOrder int32              `json:"display_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Award struct {
	ID            uuid.UUID          `json:"id"`
	DistanceID    uuid.UUID          `json:"distance_id"`
	AgeCategoryID uuid.UUID          `json:"age_category_id"`
	Gender        string             `json:"gender"`
	Place         int32              `json:"place"`
	PrizeAmount   pgtype.Numeric     `json:"prize_amount"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Distance struct {
	ID             uuid.UUID          `json:"id"`
	EventID        uuid.UUID          `json:"event_id"`
	DistanceTypeID pgtype.UUID        `json:"distance_type_id"`
	Km             pgtype.Numeric     `json:"km"`
	Capacity       int32              `json:"capacity"`
	Surface        string             `json:"surface"`
	Elevation      pgtype.Int4        `json:"elevation"`
	TimeLimit      pgtype.Text        `json:"time_limit"`
	StartLat       pgtype.Numeric     `json:"start_lat"`
	StartLng       pgtype.Numeric     `json:"start_lng"`
	EndLat         pgtype.Numeric     `json:"end_lat"`
	EndLng         pgtype.Numeric     `json:"end_lng"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type DistanceType struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Km        pgtype.Numeric     `json:"km"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID           uuid.UUID          `json:"id"`
	OrganizerID  uuid.UUID          `json:"organizer_id"`
	Name         string             `json:"name"`
	Slug         string             `json:"slug"`
	Description  pgtype.Text        `json:"description"`
	EventDate    pgtype.Timestamptz `json:"event_date"`
	Deadline     time.Time          `json:"deadline"`
	State        string             `json:"state"`
	Municipality string             `json:"municipality"`
	Address      string             `json:"address"`
	LogoUrl      string             `json:"logo_url"`
	Judges       pgtype.Text        `json:"judges"`
	Rules        pgtype.Text        `json:"rules"`
	Risks        pgtype.Text        `json:"risks"`
	Transit      pgtype.Text        `json:"transit"`
	Itinerary    []byte             `json:"itinerary"`
	Status       pgtype.Text        `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type EventFieldConfig struct {
	ID          uuid.UUID          `json:"id"`
	EventID     uuid.UUID          `json:"event_id"`
	SectionName string             `json:"section_name"`
	IsEnabled   bool               `json:"is_enabled"`
	IsRequired  bool               `json:"is_required"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type EventParticipantField struct {
	ID           uuid.UUID          `json:"id"`
	EventID      uuid.UUID          `json:"event_id"`
	FieldName    string             `json:"field_name"`
	IsRequired   bool               `json:"is_required"`
	IsEnabled    bool               `json:"is_enabled"`
	DisplayOrder pgtype.Int4        `json:"display_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type EventTag struct {
	ID        uuid.UUID          `json:"id"`
	EventID   uuid.UUID          `json:"event_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Order struct {
	ID                      uuid.UUID          `json:"id"`
	RegistrationID          uuid.UUID          `json:"registration_id"`
	ParticipantID           uuid.UUID          `json:"participant_id"`
	EventID                 uuid.UUID          `json:"event_id"`
	Amount                  pgtype.Numeric     `json:"amount"`
	Currency                string             `json:"currency"`
	Status                  pgtype.Text        `json:"status"`
	PaymentMethod           pgtype.Text        `json:"payment_method"`
	MercadoPagoPaymentID    pgtype.Text        `json:"mercado_pago_payment_id"`
	MercadoPagoPreferenceID pgtype.Text        `json:"mercado_pago_preference_id"`
	TransactionDate         pgtype.Timestamptz `json:"transaction_date"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type Organizer struct {
	ID             uuid.UUID          `json:"id"`
	BusinessName   string             `json:"business_name"`
	BrandName      pgtype.Text        `json:"brand_name"`
	Rfc            string             `json:"rfc"`
	BillingZipCode string             `json:"billing_zip_code"`
	BillingState   string             `json:"billing_state"`
	BillingCity    string             `json:"billing_city"`
	ContactName    string             `json:"contact_name"`
	ContactEmail   string             `json:"contact_email"`
	ContactPhone   string             `json:"contact_phone"`
	LogoUrl        pgtype.Text        `json:"logo_url"`
	IsActive       pgtype.Bool        `json:"is_active"`
	LastLogin      pgtype.Timestamptz `json:"last_login"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Participant struct {
	ID                    uuid.UUID          `json:"id"`
	FirstName             string             `json:"first_name"`
	LastName              string             `json:"last_name"`
	SecondLastName        pgtype.Text        `json:"second_last_name"`
	Gender                string             `json:"gender"`
	BirthDate             time.Time          `json:"birth_date"`
	Email                 string             `json:"email"`
	Phone                 string             `json:"phone"`
	Country               string             `json:"country"`
	Municipality          pgtype.Text        `json:"municipality"`
	State                 pgtype.Text        `json:"state"`
	ZipCode               pgtype.Text        `json:"zip_code"`
	Team                  pgtype.Text        `json:"team"`
	Size                  pgtype.Text        `json:"size"`
	EmergencyContactName  pgtype.Text        `json:"emergency_contact_name"`
	EmergencyContactPhone pgtype.Text        `json:"emergency_contact_phone"`
	MedicalInfo           pgtype.Text        `json:"medical_info"`
	WaiverSignedAt        pgtype.Timestamptz `json:"waiver_signed_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type PricingStage struct {
	ID          uuid.UUID          `json:"id"`
	DistanceID  uuid.UUID          `json:"distance_id"`
	Name        pgtype.Text        `json:"name"`
	Price       pgtype.Numeric     `json:"price"`
	StartDate   time.Time          `json:"start_date"`
	EndDate     time.Time          `json:"end_date"`
	IsEarlyBird pgtype.Bool        `json:"is_early_bird"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Registration struct {
	ID               uuid.UUID          `json:"id"`
	EventID          uuid.UUID          `json:"event_id"`
	ParticipantID    uuid.UUID          `json:"participant_id"`
	DistanceID       uuid.UUID          `json:"distance_id"`
	Category         string             `json:"category"`
	BibNumber        pgtype.Text        `json:"bib_number"`
	QrCode           pgtype.Text        `json:"qr_code"`
	Time             pgtype.Text        `json:"time"`
	Status           pgtype.Text        `json:"status"`
	RegistrationDate pgtype.Timestamptz `json:"registration_date"`
	CheckedInAt      pgtype.Timestamptz `json:"checked_in_at"`
}

type RegistrationLocation struct {
	ID           uuid.UUID          `json:"id"`
	EventID      uuid.UUID          `json:"event_id"`
	LocationName string             `json:"location_name"`
	Address      string             `json:"address"`
	Schedule     pgtype.Text        `json:"schedule"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Route struct {
	ID                 uuid.UUID          `json:"id"`
	EventID            uuid.UUID          `json:"event_id"`
	DistanceID         pgtype.UUID        `json:"distance_id"`
	Name               string             `json:"name"`
	Geojson            []byte             `json:"geojson"`
	ElevationProfile   []byte             `json:"elevation_profile"`
	TotalDistance      pgtype.Numeric     `json:"total_distance"`
	TotalElevationGain pgtype.Numeric     `json:"total_elevation_gain"`
	MinElevation       pgtype.Numeric     `json:"min_elevation"`
	MaxElevation       pgtype.Numeric     `json:"max_elevation"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type RunnerKitItem struct {
	ID          uuid.UUID          `json:"id"`
	EventID     uuid.UUID          `json:"event_id"`
	Name        string             `json:"name"`
	Icon        string             `json:"icon"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Sponsor struct {
	ID         uuid.UUID          `json:"id"`
	EventID    uuid.UUID          `json:"event_id"`
	Name       string             `json:"name"`
	Tier       string             `json:"tier"`
	LogoUrl    pgtype.Text        `json:"logo_url"`
	WebsiteUrl pgtype.Text        `json:"website_url"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID            uuid.UUID          `json:"id"`
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	Role          string             `json:"role"`
	OrganizerID   pgtype.UUID        `json:"organizer_id"`
	ParticipantID pgtype.UUID        `json:"participant_id"`
	IsActive      pgtype.Bool        `json:"is_active"`
	LastLogin     pgtype.Timestamptz `json:"last_login"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
