// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAward = `-- name: CreateAward :one

INSERT INTO awards (
    distance_id, age_category_id, gender, place, prize_amount
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, distance_id, age_category_id, gender, place, prize_amount, created_at
`

type CreateAwardParams struct {
	DistanceID    uuid.UUID      `json:"distance_id"`
	AgeCategoryID uuid.UUID      `json:"age_category_id"`
	Gender        string         `json:"gender"`
	Place         int32          `json:"place"`
	PrizeAmount   pgtype.Numeric `json:"prize_amount"`
}

// sqlc queries for awards
func (q *Queries) CreateAward(ctx context.Context, arg CreateAwardParams) (Award, error) {
	row := q.db.QueryRow(ctx, createAward,
		arg.DistanceID,
		arg.AgeCategoryID,
		arg.Gender,
		arg.Place,
		arg.PrizeAmount,
	)
	var i Award
	err := row.Scan(
		&i.ID,
		&i.DistanceID,
		&i.AgeCategoryID,
		&i.Gender,
		&i.Place,
		&i.PrizeAmount,
		&i.CreatedAt,
	)
	return i, err
}

const createDistance = `-- name: CreateDistance :one

INSERT INTO distances (
    event_id, distance_type_id, km, capacity, surface, elevation, time_limit, start_lat, start_lng, end_lat, end_lng
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, event_id, distance_type_id, km, capacity, surface, elevation, time_limit, start_lat, start_lng, end_lat, end_lng, created_at
`

type CreateDistanceParams struct {
	EventID        uuid.UUID      `json:"event_id"`
	DistanceTypeID pgtype.UUID    `json:"distance_type_id"`
	Km             pgtype.Numeric `json:"km"`
	Capacity       int32          `json:"capacity"`
	Surface        string         `json:"surface"`
	Elevation      pgtype.Int4    `json:"elevation"`
	TimeLimit      pgtype.Text    `json:"time_limit"`
	StartLat       pgtype.Numeric `json:"start_lat"`
	StartLng       pgtype.Numeric `json:"start_lng"`
	EndLat         pgtype.Numeric `json:"end_lat"`
	EndLng         pgtype.Numeric `json:"end_lng"`
}

// sqlc queries for distances
func (q *Queries) CreateDistance(ctx context.Context, arg CreateDistanceParams) (Distance, error) {
	row := q.db.QueryRow(ctx, createDistance,
		arg.EventID,
		arg.DistanceTypeID,
		arg.Km,
		arg.Capacity,
		arg.Surface,
		arg.Elevation,
		arg.TimeLimit,
		arg.StartLat,
		arg.StartLng,
		arg.EndLat,
		arg.EndLng,
	)
	var i Distance
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.DistanceTypeID,
		&i.Km,
		&i.Capacity,
		&i.Surface,
		&i.Elevation,
		&i.TimeLimit,
		&i.StartLat,
		&i.StartLng,
		&i.EndLat,
		&i.EndLng,
		&i.CreatedAt,
	)
	return i, err
}

const createDistanceType = `-- name: CreateDistanceType :one

INSERT INTO distance_types (name, km) VALUES ($1, $2) RETURNING id, name, km, created_at
`

type CreateDistanceTypeParams struct {
	Name string         `json:"name"`
	Km   pgtype.Numeric `json:"km"`
}

// sqlc queries for distance_types
func (q *Queries) CreateDistanceType(ctx context.Context, arg CreateDistanceTypeParams) (DistanceType, error) {
	row := q.db.QueryRow(ctx, createDistanceType, arg.Name, arg.Km)
	var i DistanceType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Km,
		&i.CreatedAt,
	)
	return i, err
}

const createEvent = `-- name: CreateEvent :one

INSERT INTO events (
    organizer_id, name, slug, description, event_date, deadline,
    state, municipality, address, logo_url, judges, rules, risks, transit, itinerary, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
) RETURNING id, organizer_id, name, slug, description, event_date, deadline, state, municipality, address, logo_url, judges, rules, risks, transit, itinerary, status, created_at, updated_at
`

type CreateEventParams struct {
	OrganizerID  uuid.UUID          `json:"organizer_id"`
	Name         string             `json:"name"`
	Slug         string             `json:"slug"`
	Description  pgtype.Text        `json:"description"`
	EventDate    pgtype.Timestamptz `json:"event_date"`
	Deadline     time.Time          `json:"deadline"`
	State        string             `json:"state"`
	Municipality string             `json:"municipality"`
	Address      string             `json:"address"`
	LogoUrl      string             `json:"logo_url"`
	Judges       pgtype.Text        `json:"judges"`
	Rules        pgtype.Text        `json:"rules"`
	Risks        pgtype.Text        `json:"risks"`
	Transit      pgtype.Text        `json:"transit"`
	Itinerary    []byte             `json:"itinerary"`
	Status       pgtype.Text        `json:"status"`
}

// sqlc queries for events
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.OrganizerID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.EventDate,
		arg.Deadline,
		arg.State,
		arg.Municipality,
		arg.Address,
		arg.LogoUrl,
		arg.Judges,
		arg.Rules,
		arg.Risks,
		arg.Transit,
		arg.Itinerary,
		arg.Status,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.EventDate,
		&i.Deadline,
		&i.State,
		&i.Municipality,
		&i.Address,
		&i.LogoUrl,
		&i.Judges,
		&i.Rules,
		&i.Risks,
		&i.Transit,
		&i.Itinerary,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEventParticipantField = `-- name: CreateEventParticipantField :one

INSERT INTO event_participant_fields (
    event_id, field_name, is_required, is_enabled, display_order
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, event_id, field_name, is_required, is_enabled, display_order, created_at
`

type CreateEventParticipantFieldParams struct {
	EventID      uuid.UUID   `json:"event_id"`
	FieldName    string      `json:"field_name"`
	IsRequired   bool        `json:"is_required"`
	IsEnabled    bool        `json:"is_enabled"`
	DisplayOrder pgtype.Int4 `json:"display_order"`
}

// sqlc queries for event_participant_fields
func (q *Queries) CreateEventParticipantField(ctx context.Context, arg CreateEventParticipantFieldParams) (EventParticipantField, error) {
	row := q.db.QueryRow(ctx, createEventParticipantField,
		arg.EventID,
		arg.FieldName,
		arg.IsRequired,
		arg.IsEnabled,
		arg.DisplayOrder,
	)
	var i EventParticipantField
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.FieldName,
		&i.IsRequired,
		&i.IsEnabled,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createEventTag = `-- name: CreateEventTag :one

INSERT INTO event_tags (event_id, name) VALUES ($1, $2) RETURNING id, event_id, name, created_at
`

type CreateEventTagParams struct {
	EventID uuid.UUID `json:"event_id"`
	Name    string    `json:"name"`
}

// sqlc queries for event_tags
func (q *Queries) CreateEventTag(ctx context.Context, arg CreateEventTagParams) (EventTag, error) {
	row := q.db.QueryRow(ctx, createEventTag, arg.EventID, arg.Name)
	var i EventTag
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one

INSERT INTO orders (
    registration_id, participant_id, event_id, amount, currency,
    status, payment_method, mercado_pago_payment_id, mercado_pago_preference_id,
    transaction_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, registration_id, participant_id, event_id, amount, currency, status, payment_method, mercado_pago_payment_id, mercado_pago_preference_id, transaction_date, created_at, updated_at
`

type CreateOrderParams struct {
	RegistrationID          uuid.UUID          `json:"registration_id"`
	ParticipantID           uuid.UUID          `json:"participant_id"`
	EventID                 uuid.UUID          `json:"event_id"`
	Amount                  pgtype.Numeric     `json:"amount"`
	Currency                string             `json:"currency"`
	Status                  pgtype.Text        `json:"status"`
	PaymentMethod           pgtype.Text        `json:"payment_method"`
	MercadoPagoPaymentID    pgtype.Text        `json:"mercado_pago_payment_id"`
	MercadoPagoPreferenceID pgtype.Text        `json:"mercado_pago_preference_id"`
	TransactionDate         pgtype.Timestamptz `json:"transaction_date"`
}

// sqlc queries for orders
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.RegistrationID,
		arg.ParticipantID,
		arg.EventID,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.PaymentMethod,
		arg.MercadoPagoPaymentID,
		arg.MercadoPagoPreferenceID,
		arg.TransactionDate,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.ParticipantID,
		&i.EventID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.MercadoPagoPaymentID,
		&i.MercadoPagoPreferenceID,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganizer = `-- name: CreateOrganizer :one

INSERT INTO organizers (
    business_name, brand_name, rfc, billing_zip_code, billing_state, billing_city,
    contact_name, contact_email, contact_phone, logo_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, business_name, brand_name, rfc, billing_zip_code, billing_state, billing_city, contact_name, contact_email, contact_phone, logo_url, is_active, last_login, created_at, updated_at
`

type CreateOrganizerParams struct {
	BusinessName   string      `json:"business_name"`
	BrandName      pgtype.Text `json:"brand_name"`
	Rfc            string      `json:"rfc"`
	BillingZipCode string      `json:"billing_zip_code"`
	BillingState   string      `json:"billing_state"`
	BillingCity    string      `json:"billing_city"`
	ContactName    string      `json:"contact_name"`
	ContactEmail   string      `json:"contact_email"`
	ContactPhone   string      `json:"contact_phone"`
	LogoUrl        pgtype.Text `json:"logo_url"`
}

// sqlc queries for organizers
func (q *Queries) CreateOrganizer(ctx context.Context, arg CreateOrganizerParams) (Organizer, error) {
	row := q.db.QueryRow(ctx, createOrganizer,
		arg.BusinessName,
		arg.BrandName,
		arg.Rfc,
		arg.BillingZipCode,
		arg.BillingState,
		arg.BillingCity,
		arg.ContactName,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.LogoUrl,
	)
	var i Organizer
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.BrandName,
		&i.Rfc,
		&i.BillingZipCode,
		&i.BillingState,
		&i.BillingCity,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.LogoUrl,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createParticipant = `-- name: CreateParticipant :one

INSERT INTO participants (
    first_name, last_name, second_last_name, gender, birth_date, email,
    phone, country, municipality, state, zip_code, team, size,
    emergency_contact_name, emergency_contact_phone, medical_info, waiver_signed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
) RETURNING id, first_name, last_name, second_last_name, gender, birth_date, email, phone, country, municipality, state, zip_code, team, size, emergency_contact_name, emergency_contact_phone, medical_info, waiver_signed_at, created_at, updated_at
`

type CreateParticipantParams struct {
	FirstName             string             `json:"first_name"`
	LastName              string             `json:"last_name"`
	SecondLastName        pgtype.Text        `json:"second_last_name"`
	Gender                string             `json:"gender"`
	BirthDate             time.Time          `json:"birth_date"`
	Email                 string             `json:"email"`
	Phone                 string             `json:"phone"`
	Country               string             `json:"country"`
	Municipality          pgtype.Text        `json:"municipality"`
	State                 pgtype.Text        `json:"state"`
	ZipCode               pgtype.Text        `json:"zip_code"`
	Team                  pgtype.Text        `json:"team"`
	Size                  pgtype.Text        `json:"size"`
	EmergencyContactName  pgtype.Text        `json:"emergency_contact_name"`
	EmergencyContactPhone pgtype.Text        `json:"emergency_contact_phone"`
	MedicalInfo           pgtype.Text        `json:"medical_info"`
	WaiverSignedAt        pgtype.Timestamptz `json:"waiver_signed_at"`
}

// sqlc queries for participants
func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) (Participant, error) {
	row := q.db.QueryRow(ctx, createParticipant,
		arg.FirstName,
		arg.LastName,
		arg.SecondLastName,
		arg.Gender,
		arg.BirthDate,
		arg.Email,
		arg.Phone,
		arg.Country,
		arg.Municipality,
		arg.State,
		arg.ZipCode,
		arg.Team,
		arg.Size,
		arg.EmergencyContactName,
		arg.EmergencyContactPhone,
		arg.MedicalInfo,
		arg.WaiverSignedAt,
	)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.SecondLastName,
		&i.Gender,
		&i.BirthDate,
		&i.Email,
		&i.Phone,
		&i.Country,
		&i.Municipality,
		&i.State,
		&i.ZipCode,
		&i.Team,
		&i.Size,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.MedicalInfo,
		&i.WaiverSignedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPricingStage = `-- name: CreatePricingStage :one

INSERT INTO pricing_stages (
    distance_id, name, price, start_date, end_date, is_early_bird
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, distance_id, name, price, start_date, end_date, is_early_bird, created_at
`

type CreatePricingStageParams struct {
	DistanceID  uuid.UUID      `json:"distance_id"`
	Name        pgtype.Text    `json:"name"`
	Price       pgtype.Numeric `json:"price"`
	StartDate   time.Time      `json:"start_date"`
	EndDate     time.Time      `json:"end_date"`
	IsEarlyBird pgtype.Bool    `json:"is_early_bird"`
}

// sqlc queries for pricing stages
func (q *Queries) CreatePricingStage(ctx context.Context, arg CreatePricingStageParams) (PricingStage, error) {
	row := q.db.QueryRow(ctx, createPricingStage,
		arg.DistanceID,
		arg.Name,
		arg.Price,
		arg.StartDate,
		arg.EndDate,
		arg.IsEarlyBird,
	)
	var i PricingStage
	err := row.Scan(
		&i.ID,
		&i.DistanceID,
		&i.Name,
		&i.Price,
		&i.StartDate,
		&i.EndDate,
		&i.IsEarlyBird,
		&i.CreatedAt,
	)
	return i, err
}

const createRegistration = `-- name: CreateRegistration :one
INSERT INTO registrations (
    event_id, participant_id, distance_id, category, bib_number, qr_code, time, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, event_id, participant_id, distance_id, category, bib_number, qr_code, time, status, registration_date, checked_in_at
`

type CreateRegistrationParams struct {
	EventID       uuid.UUID   `json:"event_id"`
	ParticipantID uuid.UUID   `json:"participant_id"`
	DistanceID    uuid.UUID   `json:"distance_id"`
	Category      string      `json:"category"`
	BibNumber     pgtype.Text `json:"bib_number"`
	QrCode        pgtype.Text `json:"qr_code"`
	Time          pgtype.Text `json:"time"`
	Status        pgtype.Text `json:"status"`
}

func (q *Queries) CreateRegistration(ctx context.Context, arg CreateRegistrationParams) (Registration, error) {
	row := q.db.QueryRow(ctx, createRegistration,
		arg.EventID,
		arg.ParticipantID,
		arg.DistanceID,
		arg.Category,
		arg.BibNumber,
		arg.QrCode,
		arg.Time,
		arg.Status,
	)
	var i Registration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ParticipantID,
		&i.DistanceID,
		&i.Category,
		&i.BibNumber,
		&i.QrCode,
		&i.Time,
		&i.Status,
		&i.RegistrationDate,
		&i.CheckedInAt,
	)
	return i, err
}

const createRegistrationLocation = `-- name: CreateRegistrationLocation :one

INSERT INTO registration_locations (
    event_id, location_name, address, schedule
) VALUES (
    $1, $2, $3, $4
) RETURNING id, event_id, location_name, address, schedule, created_at
`

type CreateRegistrationLocationParams struct {
	EventID      uuid.UUID   `json:"event_id"`
	LocationName string      `json:"location_name"`
	Address      string      `json:"address"`
	Schedule     pgtype.Text `json:"schedule"`
}

// sqlc queries for registration locations
func (q *Queries) CreateRegistrationLocation(ctx context.Context, arg CreateRegistrationLocationParams) (RegistrationLocation, error) {
	row := q.db.QueryRow(ctx, createRegistrationLocation,
		arg.EventID,
		arg.LocationName,
		arg.Address,
		arg.Schedule,
	)
	var i RegistrationLocation
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.LocationName,
		&i.Address,
		&i.Schedule,
		&i.CreatedAt,
	)
	return i, err
}

const createRoute = `-- name: CreateRoute :one

INSERT INTO routes (
    event_id, distance_id, name, geojson, elevation_profile,
    total_distance, total_elevation_gain, min_elevation, max_elevation
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
) RETURNING id, event_id, distance_id, name, geojson, elevation_profile, total_distance, total_elevation_gain, min_elevation, max_elevation, created_at
`

type CreateRouteParams struct {
	EventID            uuid.UUID      `json:"event_id"`
	DistanceID         pgtype.UUID    `json:"distance_id"`
	Name               string         `json:"name"`
	Geojson            []byte         `json:"geojson"`
	ElevationProfile   []byte         `json:"elevation_profile"`
	TotalDistance      pgtype.Numeric `json:"total_distance"`
	TotalElevationGain pgtype.Numeric `json:"total_elevation_gain"`
	MinElevation       pgtype.Numeric `json:"min_elevation"`
	MaxElevation       pgtype.Numeric `json:"max_elevation"`
}

// sqlc queries for routes
func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, createRoute,
		arg.EventID,
		arg.DistanceID,
		arg.Name,
		arg.Geojson,
		arg.ElevationProfile,
		arg.TotalDistance,
		arg.TotalElevationGain,
		arg.MinElevation,
		arg.MaxElevation,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.DistanceID,
		&i.Name,
		&i.Geojson,
		&i.ElevationProfile,
		&i.TotalDistance,
		&i.TotalElevationGain,
		&i.MinElevation,
		&i.MaxElevation,
		&i.CreatedAt,
	)
	return i, err
}

const createRunnerKitItem = `-- name: CreateRunnerKitItem :one

INSERT INTO runner_kit_items (event_id, name, icon) VALUES ($1, $2, $3) RETURNING id, event_id, name, icon, created_at
`

type CreateRunnerKitItemParams struct {
	EventID     uuid.UUID `json:"event_id"`
	Name        string    `json:"name"`
	Icon        string    `json:"icon"`
}

// sqlc queries for runner_kit_items
func (q *Queries) CreateRunnerKitItem(ctx context.Context, arg CreateRunnerKitItemParams) (RunnerKitItem, error) {
	row := q.db.QueryRow(ctx, createRunnerKitItem,
		arg.EventID,
		arg.Name,
		arg.Icon,
	)
	var i RunnerKitItem
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
	)
	return i, err
}

const createSponsor = `-- name: CreateSponsor :one

INSERT INTO sponsors (
    event_id, name, tier, logo_url, website_url
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, event_id, name, tier, logo_url, website_url, created_at
`

type CreateSponsorParams struct {
	EventID    uuid.UUID   `json:"event_id"`
	Name       string      `json:"name"`
	Tier       string      `json:"tier"`
	LogoUrl    pgtype.Text `json:"logo_url"`
	WebsiteUrl pgtype.Text `json:"website_url"`
}

// sqlc queries for sponsors
func (q *Queries) CreateSponsor(ctx context.Context, arg CreateSponsorParams) (Sponsor, error) {
	row := q.db.QueryRow(ctx, createSponsor,
		arg.EventID,
		arg.Name,
		arg.Tier,
		arg.LogoUrl,
		arg.WebsiteUrl,
	)
	var i Sponsor
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Tier,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (
    email, password_hash, role, organizer_id, participant_id
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, email, password_hash, role, organizer_id, participant_id, is_active, last_login, created_at, updated_at
`

type CreateUserParams struct {
	Email         string      `json:"email"`
	PasswordHash  string      `json:"password_hash"`
	Role          string      `json:"role"`
	OrganizerID   pgtype.UUID `json:"organizer_id"`
	ParticipantID pgtype.UUID `json:"participant_id"`
}

// sqlc queries for users
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.OrganizerID,
		arg.ParticipantID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.OrganizerID,
		&i.ParticipantID,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAward = `-- name: DeleteAward :exec
DELETE FROM awards
WHERE id = $1
`

func (q *Queries) DeleteAward(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAward, id)
	return err
}

const deleteDistance = `-- name: DeleteDistance :exec
DELETE FROM distances
WHERE id = $1
`

func (q *Queries) DeleteDistance(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDistance, id)
	return err
}

const deleteDistanceType = `-- name: DeleteDistanceType :exec
DELETE FROM distance_types WHERE id = $1
`

func (q *Queries) DeleteDistanceType(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDistanceType, id)
	return err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const deleteEventFieldConfigByEvent = `-- name: DeleteEventFieldConfigByEvent :exec
DELETE FROM event_field_config
WHERE event_id = $1
`

func (q *Queries) DeleteEventFieldConfigByEvent(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEventFieldConfigByEvent, eventID)
	return err
}

const deleteEventParticipantFieldsByEvent = `-- name: DeleteEventParticipantFieldsByEvent :exec
DELETE FROM event_participant_fields
WHERE event_id = $1
`

func (q *Queries) DeleteEventParticipantFieldsByEvent(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEventParticipantFieldsByEvent, eventID)
	return err
}

const deleteEventTag = `-- name: DeleteEventTag :exec
DELETE FROM event_tags WHERE id = $1
`

func (q *Queries) DeleteEventTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEventTag, id)
	return err
}

const deleteEventTagsByEvent = `-- name: DeleteEventTagsByEvent :exec
DELETE FROM event_tags WHERE event_id = $1
`

func (q *Queries) DeleteEventTagsByEvent(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEventTagsByEvent, eventID)
	return err
}

const deleteEventTagsByNames = `-- name: DeleteEventTagsByNames :exec
DELETE FROM event_tags WHERE event_id = $1 AND name = ANY($2::varchar(50)[])
`

type DeleteEventTagsByNamesParams struct {
	EventID uuid.UUID `json:"event_id"`
	Names   []string  `json:"names"`
}

func (q *Queries) DeleteEventTagsByNames(ctx context.Context, arg DeleteEventTagsByNamesParams) error {
	_, err := q.db.Exec(ctx, deleteEventTagsByNames, arg.EventID, arg.Names)
	return err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders
WHERE id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrder, id)
	return err
}

const deleteOrganizer = `-- name: DeleteOrganizer :exec
DELETE FROM organizers
WHERE id = $1
`

func (q *Queries) DeleteOrganizer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganizer, id)
	return err
}

const deleteParticipant = `-- name: DeleteParticipant :exec
DELETE FROM participants
WHERE id = $1
`

func (q *Queries) DeleteParticipant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteParticipant, id)
	return err
}

const deletePricingStage = `-- name: DeletePricingStage :exec
DELETE FROM pricing_stages
WHERE id = $1
`

func (q *Queries) DeletePricingStage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePricingStage, id)
	return err
}

const deleteRegistration = `-- name: DeleteRegistration :exec
DELETE FROM registrations
WHERE id = $1
`

func (q *Queries) DeleteRegistration(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRegistration, id)
	return err
}

const deleteRegistrationLocation = `-- name: DeleteRegistrationLocation :exec
DELETE FROM registration_locations
WHERE id = $1
`

func (q *Queries) DeleteRegistrationLocation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRegistrationLocation, id)
	return err
}

const deleteRoute = `-- name: DeleteRoute :exec
DELETE FROM routes WHERE id = $1
`

func (q *Queries) DeleteRoute(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoute, id)
	return err
}

const deleteRunnerKitItem = `-- name: DeleteRunnerKitItem :exec
DELETE FROM runner_kit_items WHERE id = $1
`

func (q *Queries) DeleteRunnerKitItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRunnerKitItem, id)
	return err
}

const deleteSponsor = `-- name: DeleteSponsor :exec
DELETE FROM sponsors
WHERE id = $1
`

func (q *Queries) DeleteSponsor(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSponsor, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAward = `-- name: GetAward :one
SELECT id, distance_id, age_category_id, gender, prize_amount, created_at FROM awards
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAward(ctx context.Context, id uuid.UUID) (Award, error) {
	row := q.db.QueryRow(ctx, getAward, id)
	var i Award
	err := row.Scan(
		&i.ID,
		&i.DistanceID,
		&i.AgeCategoryID,
		&i.Gender,
		&i.PrizeAmount,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentPricing = `-- name: GetCurrentPricing :many
SELECT id, distance_id, name, price, start_date, end_date, is_early_bird, created_at FROM pricing_stages
WHERE distance_id = $1
  AND start_date <= CURRENT_DATE
  AND end_date >= CURRENT_DATE
ORDER BY price ASC
`

func (q *Queries) GetCurrentPricing(ctx context.Context, distanceID uuid.UUID) ([]PricingStage, error) {
	rows, err := q.db.Query(ctx, getCurrentPricing, distanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PricingStage{}
	for rows.Next() {
		var i PricingStage
		if err := rows.Scan(
			&i.ID,
			&i.DistanceID,
			&i.Name,
			&i.Price,
			&i.StartDate,
			&i.EndDate,
			&i.IsEarlyBird,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistance = `-- name: GetDistance :one
SELECT id, event_id, distance_type_id, km, capacity, surface, elevation, time_limit, start_lat, start_lng, end_lat, end_lng, created_at FROM distances
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDistance(ctx context.Context, id uuid.UUID) (Distance, error) {
	row := q.db.QueryRow(ctx, getDistance, id)
	var i Distance
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.DistanceTypeID,
		&i.Km,
		&i.Capacity,
		&i.Surface,
		&i.Elevation,
		&i.TimeLimit,
		&i.StartLat,
		&i.StartLng,
		&i.EndLat,
		&i.EndLng,
		&i.CreatedAt,
	)
	return i, err
}

const getDistanceByEventAndType = `-- name: GetDistanceByEventAndType :one
SELECT id, event_id, distance_type_id, km, capacity, surface, elevation, time_limit, start_lat, start_lng, end_lat, end_lng, created_at FROM distances
WHERE event_id = $1 AND distance_type_id = $2
LIMIT 1
`

type GetDistanceByEventAndTypeParams struct {
	EventID        uuid.UUID   `json:"event_id"`
	DistanceTypeID pgtype.UUID `json:"distance_type_id"`
}

func (q *Queries) GetDistanceByEventAndType(ctx context.Context, arg GetDistanceByEventAndTypeParams) (Distance, error) {
	row := q.db.QueryRow(ctx, getDistanceByEventAndType, arg.EventID, arg.DistanceTypeID)
	var i Distance
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.DistanceTypeID,
		&i.Km,
		&i.Capacity,
		&i.Surface,
		&i.Elevation,
		&i.TimeLimit,
		&i.StartLat,
		&i.StartLng,
		&i.EndLat,
		&i.EndLng,
		&i.CreatedAt,
	)
	return i, err
}

const getDistanceType = `-- name: GetDistanceType :one
SELECT id, name, km, created_at FROM distance_types WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDistanceType(ctx context.Context, id uuid.UUID) (DistanceType, error) {
	row := q.db.QueryRow(ctx, getDistanceType, id)
	var i DistanceType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Km,
		&i.CreatedAt,
	)
	return i, err
}

const getDistanceTypeByKM = `-- name: GetDistanceTypeByKM :one
SELECT id, name, km, created_at FROM distance_types WHERE km = $1 LIMIT 1
`

func (q *Queries) GetDistanceTypeByKM(ctx context.Context, km pgtype.Numeric) (DistanceType, error) {
	row := q.db.QueryRow(ctx, getDistanceTypeByKM, km)
	var i DistanceType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Km,
		&i.CreatedAt,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, organizer_id, name, slug, description, event_date, deadline, state, municipality, address, logo_url, judges, rules, risks, transit, itinerary, status, created_at, updated_at FROM events
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEvent(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.EventDate,
		&i.Deadline,
		&i.State,
		&i.Municipality,
		&i.Address,
		&i.LogoUrl,
		&i.Judges,
		&i.Rules,
		&i.Risks,
		&i.Transit,
		&i.Itinerary,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventBySlug = `-- name: GetEventBySlug :one
SELECT id, organizer_id, name, slug, description, event_date, deadline, state, municipality, address, logo_url, judges, rules, risks, transit, itinerary, status, created_at, updated_at FROM events
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetEventBySlug(ctx context.Context, slug string) (Event, error) {
	row := q.db.QueryRow(ctx, getEventBySlug, slug)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.EventDate,
		&i.Deadline,
		&i.State,
		&i.Municipality,
		&i.Address,
		&i.LogoUrl,
		&i.Judges,
		&i.Rules,
		&i.Risks,
		&i.Transit,
		&i.Itinerary,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventParticipantField = `-- name: GetEventParticipantField :one
SELECT id, event_id, field_name, is_required, is_enabled, display_order, created_at FROM event_participant_fields
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEventParticipantField(ctx context.Context, id uuid.UUID) (EventParticipantField, error) {
	row := q.db.QueryRow(ctx, getEventParticipantField, id)
	var i EventParticipantField
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.FieldName,
		&i.IsRequired,
		&i.IsEnabled,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getEventTag = `-- name: GetEventTag :one
SELECT id, event_id, name, created_at FROM event_tags WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEventTag(ctx context.Context, id uuid.UUID) (EventTag, error) {
	row := q.db.QueryRow(ctx, getEventTag, id)
	var i EventTag
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getMaxBibNumberByEvent = `-- name: GetMaxBibNumberByEvent :one

SELECT COALESCE(MAX(SUBSTRING(bib_number FROM '^[0-9]+$')::INTEGER), 0) as max_num
FROM registrations
WHERE event_id = $1 AND bib_number IS NOT NULL
`

// sqlc queries for registrations
func (q *Queries) GetMaxBibNumberByEvent(ctx context.Context, eventID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getMaxBibNumberByEvent, eventID)
	var max_num interface{}
	err := row.Scan(&max_num)
	return max_num, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, registration_id, participant_id, event_id, amount, currency, status, payment_method, mercado_pago_payment_id, mercado_pago_preference_id, transaction_date, created_at, updated_at FROM orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.ParticipantID,
		&i.EventID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.MercadoPagoPaymentID,
		&i.MercadoPagoPreferenceID,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByMercadoPagoPaymentId = `-- name: GetOrderByMercadoPagoPaymentId :one
SELECT id, registration_id, participant_id, event_id, amount, currency, status, payment_method, mercado_pago_payment_id, mercado_pago_preference_id, transaction_date, created_at, updated_at FROM orders
WHERE mercado_pago_payment_id = $1 LIMIT 1
`

func (q *Queries) GetOrderByMercadoPagoPaymentId(ctx context.Context, mercadoPagoPaymentID pgtype.Text) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByMercadoPagoPaymentId, mercadoPagoPaymentID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.ParticipantID,
		&i.EventID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.MercadoPagoPaymentID,
		&i.MercadoPagoPreferenceID,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByRegistrationId = `-- name: GetOrderByRegistrationId :one
SELECT id, registration_id, participant_id, event_id, amount, currency, status, payment_method, mercado_pago_payment_id, mercado_pago_preference_id, transaction_date, created_at, updated_at FROM orders
WHERE registration_id = $1 LIMIT 1
`

func (q *Queries) GetOrderByRegistrationId(ctx context.Context, registrationID uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByRegistrationId, registrationID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.ParticipantID,
		&i.EventID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.MercadoPagoPaymentID,
		&i.MercadoPagoPreferenceID,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizer = `-- name: GetOrganizer :one
SELECT id, business_name, brand_name, rfc, billing_zip_code, billing_state, billing_city, contact_name, contact_email, contact_phone, logo_url, is_active, last_login, created_at, updated_at FROM organizers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrganizer(ctx context.Context, id uuid.UUID) (Organizer, error) {
	row := q.db.QueryRow(ctx, getOrganizer, id)
	var i Organizer
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.BrandName,
		&i.Rfc,
		&i.BillingZipCode,
		&i.BillingState,
		&i.BillingCity,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.LogoUrl,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizerByRFC = `-- name: GetOrganizerByRFC :one
SELECT id, business_name, brand_name, rfc, billing_zip_code, billing_state, billing_city, contact_name, contact_email, contact_phone, logo_url, is_active, last_login, created_at, updated_at FROM organizers
WHERE rfc = $1 LIMIT 1
`

func (q *Queries) GetOrganizerByRFC(ctx context.Context, rfc string) (Organizer, error) {
	row := q.db.QueryRow(ctx, getOrganizerByRFC, rfc)
	var i Organizer
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.BrandName,
		&i.Rfc,
		&i.BillingZipCode,
		&i.BillingState,
		&i.BillingCity,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.LogoUrl,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParticipant = `-- name: GetParticipant :one
SELECT id, first_name, last_name, second_last_name, gender, birth_date, email, phone, country, municipality, state, zip_code, team, size, emergency_contact_name, emergency_contact_phone, medical_info, waiver_signed_at, created_at, updated_at FROM participants
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetParticipant(ctx context.Context, id uuid.UUID) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipant, id)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.SecondLastName,
		&i.Gender,
		&i.BirthDate,
		&i.Email,
		&i.Phone,
		&i.Country,
		&i.Municipality,
		&i.State,
		&i.ZipCode,
		&i.Team,
		&i.Size,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.MedicalInfo,
		&i.WaiverSignedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParticipantByEmail = `-- name: GetParticipantByEmail :one
SELECT id, first_name, last_name, second_last_name, gender, birth_date, email, phone, country, municipality, state, zip_code, team, size, emergency_contact_name, emergency_contact_phone, medical_info, waiver_signed_at, created_at, updated_at FROM participants
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetParticipantByEmail(ctx context.Context, email string) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipantByEmail, email)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.SecondLastName,
		&i.Gender,
		&i.BirthDate,
		&i.Email,
		&i.Phone,
		&i.Country,
		&i.Municipality,
		&i.State,
		&i.ZipCode,
		&i.Team,
		&i.Size,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.MedicalInfo,
		&i.WaiverSignedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPricingStage = `-- name: GetPricingStage :one
SELECT id, distance_id, name, price, start_date, end_date, is_early_bird, created_at FROM pricing_stages
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPricingStage(ctx context.Context, id uuid.UUID) (PricingStage, error) {
	row := q.db.QueryRow(ctx, getPricingStage, id)
	var i PricingStage
	err := row.Scan(
		&i.ID,
		&i.DistanceID,
		&i.Name,
		&i.Price,
		&i.StartDate,
		&i.EndDate,
		&i.IsEarlyBird,
		&i.CreatedAt,
	)
	return i, err
}

const getRegistration = `-- name: GetRegistration :one
SELECT id, event_id, participant_id, distance_id, category, bib_number, qr_code, time, status, registration_date, checked_in_at FROM registrations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRegistration(ctx context.Context, id uuid.UUID) (Registration, error) {
	row := q.db.QueryRow(ctx, getRegistration, id)
	var i Registration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ParticipantID,
		&i.DistanceID,
		&i.Category,
		&i.BibNumber,
		&i.QrCode,
		&i.Time,
		&i.Status,
		&i.RegistrationDate,
		&i.CheckedInAt,
	)
	return i, err
}

const getRegistrationByBibNumber = `-- name: GetRegistrationByBibNumber :one
SELECT id, event_id, participant_id, distance_id, category, bib_number, qr_code, time, status, registration_date, checked_in_at FROM registrations
WHERE event_id = $1 AND bib_number = $2 LIMIT 1
`

type GetRegistrationByBibNumberParams struct {
	EventID   uuid.UUID   `json:"event_id"`
	BibNumber pgtype.Text `json:"bib_number"`
}

func (q *Queries) GetRegistrationByBibNumber(ctx context.Context, arg GetRegistrationByBibNumberParams) (Registration, error) {
	row := q.db.QueryRow(ctx, getRegistrationByBibNumber, arg.EventID, arg.BibNumber)
	var i Registration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ParticipantID,
		&i.DistanceID,
		&i.Category,
		&i.BibNumber,
		&i.QrCode,
		&i.Time,
		&i.Status,
		&i.RegistrationDate,
		&i.CheckedInAt,
	)
	return i, err
}

const getRegistrationByEventParticipant = `-- name: GetRegistrationByEventParticipant :one
SELECT id, event_id, participant_id, distance_id, category, bib_number, qr_code, time, status, registration_date, checked_in_at FROM registrations
WHERE event_id = $1 AND participant_id = $2 LIMIT 1
`

type GetRegistrationByEventParticipantParams struct {
	EventID       uuid.UUID `json:"event_id"`
	ParticipantID uuid.UUID `json:"participant_id"`
}

func (q *Queries) GetRegistrationByEventParticipant(ctx context.Context, arg GetRegistrationByEventParticipantParams) (Registration, error) {
	row := q.db.QueryRow(ctx, getRegistrationByEventParticipant, arg.EventID, arg.ParticipantID)
	var i Registration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ParticipantID,
		&i.DistanceID,
		&i.Category,
		&i.BibNumber,
		&i.QrCode,
		&i.Time,
		&i.Status,
		&i.RegistrationDate,
		&i.CheckedInAt,
	)
	return i, err
}

const getRegistrationLocation = `-- name: GetRegistrationLocation :one
SELECT id, event_id, location_name, address, schedule, created_at FROM registration_locations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRegistrationLocation(ctx context.Context, id uuid.UUID) (RegistrationLocation, error) {
	row := q.db.QueryRow(ctx, getRegistrationLocation, id)
	var i RegistrationLocation
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.LocationName,
		&i.Address,
		&i.Schedule,
		&i.CreatedAt,
	)
	return i, err
}

const getRoute = `-- name: GetRoute :one
SELECT id, event_id, distance_id, name, geojson, elevation_profile, total_distance, total_elevation_gain, min_elevation, max_elevation, created_at FROM routes WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRoute(ctx context.Context, id uuid.UUID) (Route, error) {
	row := q.db.QueryRow(ctx, getRoute, id)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.DistanceID,
		&i.Name,
		&i.Geojson,
		&i.ElevationProfile,
		&i.TotalDistance,
		&i.TotalElevationGain,
		&i.MinElevation,
		&i.MaxElevation,
		&i.CreatedAt,
	)
	return i, err
}

const getRunnerKitItem = `-- name: GetRunnerKitItem :one
SELECT id, event_id, name, icon, created_at FROM runner_kit_items WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRunnerKitItem(ctx context.Context, id uuid.UUID) (RunnerKitItem, error) {
	row := q.db.QueryRow(ctx, getRunnerKitItem, id)
	var i RunnerKitItem
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
	)
	return i, err
}

const getSponsor = `-- name: GetSponsor :one
SELECT id, event_id, name, tier, logo_url, website_url, created_at FROM sponsors
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSponsor(ctx context.Context, id uuid.UUID) (Sponsor, error) {
	row := q.db.QueryRow(ctx, getSponsor, id)
	var i Sponsor
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Tier,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, organizer_id, participant_id, is_active, last_login, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.OrganizerID,
		&i.ParticipantID,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, organizer_id, participant_id, is_active, last_login, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.OrganizerID,
		&i.ParticipantID,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByOrganizerID = `-- name: GetUserByOrganizerID :one
SELECT id, email, password_hash, role, organizer_id, participant_id, is_active, last_login, created_at, updated_at FROM users
WHERE organizer_id = $1 LIMIT 1
`

func (q *Queries) GetUserByOrganizerID(ctx context.Context, organizerID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOrganizerID, organizerID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.OrganizerID,
		&i.ParticipantID,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByParticipantID = `-- name: GetUserByParticipantID :one
SELECT id, email, password_hash, role, organizer_id, participant_id, is_active, last_login, created_at, updated_at FROM users
WHERE participant_id = $1 LIMIT 1
`

func (q *Queries) GetUserByParticipantID(ctx context.Context, participantID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByParticipantID, participantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.OrganizerID,
		&i.ParticipantID,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgeCategories = `-- name: ListAgeCategories :many

SELECT id, name, min_age, max_age, display_order, created_at FROM age_categories ORDER BY display_order ASC
`

// sqlc queries for age_categories
func (q *Queries) ListAgeCategories(ctx context.Context) ([]AgeCategory, error) {
	rows, err := q.db.Query(ctx, listAgeCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgeCategory{}
	for rows.Next() {
		var i AgeCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MinAge,
			&i.MaxAge,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAwardsByDistance = `-- name: ListAwardsByDistance :many
SELECT id, distance_id, age_category_id, gender, prize_amount, created_at FROM awards
WHERE distance_id = $1
ORDER BY age_category_id
`

func (q *Queries) ListAwardsByDistance(ctx context.Context, distanceID uuid.UUID) ([]Award, error) {
	rows, err := q.db.Query(ctx, listAwardsByDistance, distanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Award{}
	for rows.Next() {
		var i Award
		if err := rows.Scan(
			&i.ID,
			&i.DistanceID,
			&i.AgeCategoryID,
			&i.Gender,
			&i.PrizeAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistanceTypes = `-- name: ListDistanceTypes :many
SELECT id, name, km, created_at FROM distance_types ORDER BY km ASC
`

func (q *Queries) ListDistanceTypes(ctx context.Context) ([]DistanceType, error) {
	rows, err := q.db.Query(ctx, listDistanceTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DistanceType{}
	for rows.Next() {
		var i DistanceType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Km,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistancesByEvent = `-- name: ListDistancesByEvent :many
SELECT id, event_id, distance_type_id, km, capacity, surface, elevation, time_limit, start_lat, start_lng, end_lat, end_lng, created_at FROM distances
WHERE event_id = $1
ORDER BY km ASC
`

func (q *Queries) ListDistancesByEvent(ctx context.Context, eventID uuid.UUID) ([]Distance, error) {
	rows, err := q.db.Query(ctx, listDistancesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Distance{}
	for rows.Next() {
		var i Distance
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.DistanceTypeID,
			&i.Km,
			&i.Capacity,
			&i.Surface,
			&i.Elevation,
			&i.TimeLimit,
			&i.StartLat,
			&i.StartLng,
			&i.EndLat,
			&i.EndLng,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventFieldConfigByEvent = `-- name: ListEventFieldConfigByEvent :many

SELECT id, event_id, section_name, is_enabled, is_required, created_at, updated_at FROM event_field_config
WHERE event_id = $1
ORDER BY section_name ASC
`

// sqlc queries for event_field_config
func (q *Queries) ListEventFieldConfigByEvent(ctx context.Context, eventID uuid.UUID) ([]EventFieldConfig, error) {
	rows, err := q.db.Query(ctx, listEventFieldConfigByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventFieldConfig{}
	for rows.Next() {
		var i EventFieldConfig
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.SectionName,
			&i.IsEnabled,
			&i.IsRequired,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventParticipantFieldsByEvent = `-- name: ListEventParticipantFieldsByEvent :many
SELECT id, event_id, field_name, is_required, is_enabled, display_order, created_at FROM event_participant_fields
WHERE event_id = $1
ORDER BY display_order ASC
`

func (q *Queries) ListEventParticipantFieldsByEvent(ctx context.Context, eventID uuid.UUID) ([]EventParticipantField, error) {
	rows, err := q.db.Query(ctx, listEventParticipantFieldsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventParticipantField{}
	for rows.Next() {
		var i EventParticipantField
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.FieldName,
			&i.IsRequired,
			&i.IsEnabled,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventTagsByEvent = `-- name: ListEventTagsByEvent :many
SELECT id, event_id, name, created_at FROM event_tags WHERE event_id = $1 ORDER BY name ASC
`

func (q *Queries) ListEventTagsByEvent(ctx context.Context, eventID uuid.UUID) ([]EventTag, error) {
	rows, err := q.db.Query(ctx, listEventTagsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventTag{}
	for rows.Next() {
		var i EventTag
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventTagsByNames = `-- name: ListEventTagsByNames :many
SELECT id, event_id, name, created_at FROM event_tags WHERE event_id = $1 AND name = ANY($2::varchar(50)[]) ORDER BY name ASC
`

type ListEventTagsByNamesParams struct {
	EventID uuid.UUID `json:"event_id"`
	Column2 []string  `json:"column_2"`
}

func (q *Queries) ListEventTagsByNames(ctx context.Context, arg ListEventTagsByNamesParams) ([]EventTag, error) {
	rows, err := q.db.Query(ctx, listEventTagsByNames, arg.EventID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventTag{}
	for rows.Next() {
		var i EventTag
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, organizer_id, name, slug, description, event_date, deadline, state, municipality, address, logo_url, judges, rules, risks, transit, itinerary, status, created_at, updated_at FROM events
WHERE status = COALESCE($1, status)
ORDER BY event_date DESC
LIMIT $2 OFFSET $3
`

type ListEventsParams struct {
	Status pgtype.Text `json:"status"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.EventDate,
			&i.Deadline,
			&i.State,
			&i.Municipality,
			&i.Address,
			&i.LogoUrl,
			&i.Judges,
			&i.Rules,
			&i.Risks,
			&i.Transit,
			&i.Itinerary,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByOrganizer = `-- name: ListEventsByOrganizer :many
SELECT id, organizer_id, name, slug, description, event_date, deadline, state, municipality, address, logo_url, judges, rules, risks, transit, itinerary, status, created_at, updated_at FROM events
WHERE organizer_id = $1
ORDER BY event_date DESC
`

func (q *Queries) ListEventsByOrganizer(ctx context.Context, organizerID uuid.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByOrganizer, organizerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.EventDate,
			&i.Deadline,
			&i.State,
			&i.Municipality,
			&i.Address,
			&i.LogoUrl,
			&i.Judges,
			&i.Rules,
			&i.Risks,
			&i.Transit,
			&i.Itinerary,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByEvent = `-- name: ListOrdersByEvent :many
SELECT id, registration_id, participant_id, event_id, amount, currency, status, payment_method, mercado_pago_payment_id, mercado_pago_preference_id, transaction_date, created_at, updated_at FROM orders
WHERE event_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByEvent(ctx context.Context, eventID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.RegistrationID,
			&i.ParticipantID,
			&i.EventID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.PaymentMethod,
			&i.MercadoPagoPaymentID,
			&i.MercadoPagoPreferenceID,
			&i.TransactionDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByParticipant = `-- name: ListOrdersByParticipant :many
SELECT id, registration_id, participant_id, event_id, amount, currency, status, payment_method, mercado_pago_payment_id, mercado_pago_preference_id, transaction_date, created_at, updated_at FROM orders
WHERE participant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByParticipant(ctx context.Context, participantID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByParticipant, participantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.RegistrationID,
			&i.ParticipantID,
			&i.EventID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.PaymentMethod,
			&i.MercadoPagoPaymentID,
			&i.MercadoPagoPreferenceID,
			&i.TransactionDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByStatus = `-- name: ListOrdersByStatus :many
SELECT id, registration_id, participant_id, event_id, amount, currency, status, payment_method, mercado_pago_payment_id, mercado_pago_preference_id, transaction_date, created_at, updated_at FROM orders
WHERE status = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByStatus(ctx context.Context, status pgtype.Text) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.RegistrationID,
			&i.ParticipantID,
			&i.EventID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.PaymentMethod,
			&i.MercadoPagoPaymentID,
			&i.MercadoPagoPreferenceID,
			&i.TransactionDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizers = `-- name: ListOrganizers :many
SELECT id, business_name, brand_name, rfc, billing_zip_code, billing_state, billing_city, contact_name, contact_email, contact_phone, logo_url, is_active, last_login, created_at, updated_at FROM organizers
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListOrganizersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOrganizers(ctx context.Context, arg ListOrganizersParams) ([]Organizer, error) {
	rows, err := q.db.Query(ctx, listOrganizers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organizer{}
	for rows.Next() {
		var i Organizer
		if err := rows.Scan(
			&i.ID,
			&i.BusinessName,
			&i.BrandName,
			&i.Rfc,
			&i.BillingZipCode,
			&i.BillingState,
			&i.BillingCity,
			&i.ContactName,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.LogoUrl,
			&i.IsActive,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipants = `-- name: ListParticipants :many
SELECT id, first_name, last_name, second_last_name, gender, birth_date, email, phone, country, municipality, state, zip_code, team, size, emergency_contact_name, emergency_contact_phone, medical_info, waiver_signed_at, created_at, updated_at FROM participants
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListParticipantsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListParticipants(ctx context.Context, arg ListParticipantsParams) ([]Participant, error) {
	rows, err := q.db.Query(ctx, listParticipants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Participant{}
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.SecondLastName,
			&i.Gender,
			&i.BirthDate,
			&i.Email,
			&i.Phone,
			&i.Country,
			&i.Municipality,
			&i.State,
			&i.ZipCode,
			&i.Team,
			&i.Size,
			&i.EmergencyContactName,
			&i.EmergencyContactPhone,
			&i.MedicalInfo,
			&i.WaiverSignedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricingStagesByDistance = `-- name: ListPricingStagesByDistance :many
SELECT id, distance_id, name, price, start_date, end_date, is_early_bird, created_at FROM pricing_stages
WHERE distance_id = $1
ORDER BY start_date ASC
`

func (q *Queries) ListPricingStagesByDistance(ctx context.Context, distanceID uuid.UUID) ([]PricingStage, error) {
	rows, err := q.db.Query(ctx, listPricingStagesByDistance, distanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PricingStage{}
	for rows.Next() {
		var i PricingStage
		if err := rows.Scan(
			&i.ID,
			&i.DistanceID,
			&i.Name,
			&i.Price,
			&i.StartDate,
			&i.EndDate,
			&i.IsEarlyBird,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistrationLocationsByEvent = `-- name: ListRegistrationLocationsByEvent :many
SELECT id, event_id, location_name, address, schedule, created_at FROM registration_locations
WHERE event_id = $1
ORDER BY location_name
`

func (q *Queries) ListRegistrationLocationsByEvent(ctx context.Context, eventID uuid.UUID) ([]RegistrationLocation, error) {
	rows, err := q.db.Query(ctx, listRegistrationLocationsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegistrationLocation{}
	for rows.Next() {
		var i RegistrationLocation
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.LocationName,
			&i.Address,
			&i.Schedule,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistrationsByEvent = `-- name: ListRegistrationsByEvent :many
SELECT id, event_id, participant_id, distance_id, category, bib_number, qr_code, time, status, registration_date, checked_in_at FROM registrations
WHERE event_id = $1
ORDER BY registration_date DESC
`

func (q *Queries) ListRegistrationsByEvent(ctx context.Context, eventID uuid.UUID) ([]Registration, error) {
	rows, err := q.db.Query(ctx, listRegistrationsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Registration{}
	for rows.Next() {
		var i Registration
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ParticipantID,
			&i.DistanceID,
			&i.Category,
			&i.BibNumber,
			&i.QrCode,
			&i.Time,
			&i.Status,
			&i.RegistrationDate,
			&i.CheckedInAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistrationsByParticipant = `-- name: ListRegistrationsByParticipant :many
SELECT id, event_id, participant_id, distance_id, category, bib_number, qr_code, time, status, registration_date, checked_in_at FROM registrations
WHERE participant_id = $1
ORDER BY registration_date DESC
`

func (q *Queries) ListRegistrationsByParticipant(ctx context.Context, participantID uuid.UUID) ([]Registration, error) {
	rows, err := q.db.Query(ctx, listRegistrationsByParticipant, participantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Registration{}
	for rows.Next() {
		var i Registration
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ParticipantID,
			&i.DistanceID,
			&i.Category,
			&i.BibNumber,
			&i.QrCode,
			&i.Time,
			&i.Status,
			&i.RegistrationDate,
			&i.CheckedInAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutesByDistance = `-- name: ListRoutesByDistance :many
SELECT id, event_id, distance_id, name, geojson, elevation_profile, total_distance, total_elevation_gain, min_elevation, max_elevation, created_at FROM routes WHERE distance_id = $1 ORDER BY name ASC
`

func (q *Queries) ListRoutesByDistance(ctx context.Context, distanceID pgtype.UUID) ([]Route, error) {
	rows, err := q.db.Query(ctx, listRoutesByDistance, distanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Route{}
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.DistanceID,
			&i.Name,
			&i.Geojson,
			&i.ElevationProfile,
			&i.TotalDistance,
			&i.TotalElevationGain,
			&i.MinElevation,
			&i.MaxElevation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutesByEvent = `-- name: ListRoutesByEvent :many
SELECT id, event_id, distance_id, name, geojson, elevation_profile, total_distance, total_elevation_gain, min_elevation, max_elevation, created_at FROM routes WHERE event_id = $1 ORDER BY name ASC
`

func (q *Queries) ListRoutesByEvent(ctx context.Context, eventID uuid.UUID) ([]Route, error) {
	rows, err := q.db.Query(ctx, listRoutesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Route{}
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.DistanceID,
			&i.Name,
			&i.Geojson,
			&i.ElevationProfile,
			&i.TotalDistance,
			&i.TotalElevationGain,
			&i.MinElevation,
			&i.MaxElevation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunnerKitItemsByEvent = `-- name: ListRunnerKitItemsByEvent :many
SELECT id, event_id, name, icon, created_at FROM runner_kit_items WHERE event_id = $1 ORDER BY name ASC
`

func (q *Queries) ListRunnerKitItemsByEvent(ctx context.Context, eventID uuid.UUID) ([]RunnerKitItem, error) {
	rows, err := q.db.Query(ctx, listRunnerKitItemsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunnerKitItem{}
	for rows.Next() {
		var i RunnerKitItem
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Icon,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSponsorsByEvent = `-- name: ListSponsorsByEvent :many
SELECT id, event_id, name, tier, logo_url, website_url, created_at FROM sponsors
WHERE event_id = $1
ORDER BY tier
`

func (q *Queries) ListSponsorsByEvent(ctx context.Context, eventID uuid.UUID) ([]Sponsor, error) {
	rows, err := q.db.Query(ctx, listSponsorsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sponsor{}
	for rows.Next() {
		var i Sponsor
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Tier,
			&i.LogoUrl,
			&i.WebsiteUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAward = `-- name: UpdateAward :one
UPDATE awards
SET age_category_id = $2, gender = $3, place = $4, prize_amount = $5
WHERE id = $1
RETURNING id, distance_id, age_category_id, gender, place, prize_amount, created_at
`

type UpdateAwardParams struct {
	ID            uuid.UUID      `json:"id"`
	AgeCategoryID uuid.UUID      `json:"age_category_id"`
	Gender        string         `json:"gender"`
	Place         int32          `json:"place"`
	PrizeAmount   pgtype.Numeric `json:"prize_amount"`
}

func (q *Queries) UpdateAward(ctx context.Context, arg UpdateAwardParams) (Award, error) {
	row := q.db.QueryRow(ctx, updateAward,
		arg.ID,
		arg.AgeCategoryID,
		arg.Gender,
		arg.Place,
		arg.PrizeAmount,
	)
	var i Award
	err := row.Scan(
		&i.ID,
		&i.DistanceID,
		&i.AgeCategoryID,
		&i.Gender,
		&i.Place,
		&i.PrizeAmount,
		&i.CreatedAt,
	)
	return i, err
}

const updateDistance = `-- name: UpdateDistance :one
UPDATE distances
SET distance_type_id = $2, km = $3, capacity = $4, surface = $5, elevation = $6, time_limit = $7, start_lat = $8, start_lng = $9, end_lat = $10, end_lng = $11
WHERE id = $1
RETURNING id, event_id, distance_type_id, km, capacity, surface, elevation, time_limit, start_lat, start_lng, end_lat, end_lng, created_at
`

type UpdateDistanceParams struct {
	ID             uuid.UUID      `json:"id"`
	DistanceTypeID pgtype.UUID    `json:"distance_type_id"`
	Km             pgtype.Numeric `json:"km"`
	Capacity       int32          `json:"capacity"`
	Surface        string         `json:"surface"`
	Elevation      pgtype.Int4    `json:"elevation"`
	TimeLimit      pgtype.Text    `json:"time_limit"`
	StartLat       pgtype.Numeric `json:"start_lat"`
	StartLng       pgtype.Numeric `json:"start_lng"`
	EndLat         pgtype.Numeric `json:"end_lat"`
	EndLng         pgtype.Numeric `json:"end_lng"`
}

func (q *Queries) UpdateDistance(ctx context.Context, arg UpdateDistanceParams) (Distance, error) {
	row := q.db.QueryRow(ctx, updateDistance,
		arg.ID,
		arg.DistanceTypeID,
		arg.Km,
		arg.Capacity,
		arg.Surface,
		arg.Elevation,
		arg.TimeLimit,
		arg.StartLat,
		arg.StartLng,
		arg.EndLat,
		arg.EndLng,
	)
	var i Distance
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.DistanceTypeID,
		&i.Km,
		&i.Capacity,
		&i.Surface,
		&i.Elevation,
		&i.TimeLimit,
		&i.StartLat,
		&i.StartLng,
		&i.EndLat,
		&i.EndLng,
		&i.CreatedAt,
	)
	return i, err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET
    name = $2,
    slug = $3,
    description = $4,
    event_date = $5,
    deadline = $6,
    state = $7,
    municipality = $8,
    address = $9,
    logo_url = $10,
    judges = $11,
    rules = $12,
    risks = $13,
    transit = $14,
    itinerary = $15,
    status = $16,
    updated_at = NOW()
WHERE id = $1
RETURNING id, organizer_id, name, slug, description, event_date, deadline, state, municipality, address, logo_url, judges, rules, risks, transit, itinerary, status, created_at, updated_at
`

type UpdateEventParams struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Slug         string             `json:"slug"`
	Description  pgtype.Text        `json:"description"`
	EventDate    pgtype.Timestamptz `json:"event_date"`
	Deadline     time.Time          `json:"deadline"`
	State        string             `json:"state"`
	Municipality string             `json:"municipality"`
	Address      string             `json:"address"`
	LogoUrl      string             `json:"logo_url"`
	Judges       pgtype.Text        `json:"judges"`
	Rules        pgtype.Text        `json:"rules"`
	Risks        pgtype.Text        `json:"risks"`
	Transit      pgtype.Text        `json:"transit"`
	Itinerary    []byte             `json:"itinerary"`
	Status       pgtype.Text        `json:"status"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.EventDate,
		arg.Deadline,
		arg.State,
		arg.Municipality,
		arg.Address,
		arg.LogoUrl,
		arg.Judges,
		arg.Rules,
		arg.Risks,
		arg.Transit,
		arg.Itinerary,
		arg.Status,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.EventDate,
		&i.Deadline,
		&i.State,
		&i.Municipality,
		&i.Address,
		&i.LogoUrl,
		&i.Judges,
		&i.Rules,
		&i.Risks,
		&i.Transit,
		&i.Itinerary,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEventStatus = `-- name: UpdateEventStatus :one
UPDATE events
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, organizer_id, name, slug, description, event_date, deadline, state, municipality, address, logo_url, judges, rules, risks, transit, itinerary, status, created_at, updated_at
`

type UpdateEventStatusParams struct {
	ID     uuid.UUID   `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateEventStatus(ctx context.Context, arg UpdateEventStatusParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEventStatus, arg.ID, arg.Status)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.EventDate,
		&i.Deadline,
		&i.State,
		&i.Municipality,
		&i.Address,
		&i.LogoUrl,
		&i.Judges,
		&i.Rules,
		&i.Risks,
		&i.Transit,
		&i.Itinerary,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderPaymentInfo = `-- name: UpdateOrderPaymentInfo :one
UPDATE orders
SET
    payment_method = $2,
    mercado_pago_payment_id = $3,
    transaction_date = $4,
    status = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, registration_id, participant_id, event_id, amount, currency, status, payment_method, mercado_pago_payment_id, mercado_pago_preference_id, transaction_date, created_at, updated_at
`

type UpdateOrderPaymentInfoParams struct {
	ID                   uuid.UUID          `json:"id"`
	PaymentMethod        pgtype.Text        `json:"payment_method"`
	MercadoPagoPaymentID pgtype.Text        `json:"mercado_pago_payment_id"`
	TransactionDate      pgtype.Timestamptz `json:"transaction_date"`
	Status               pgtype.Text        `json:"status"`
}

func (q *Queries) UpdateOrderPaymentInfo(ctx context.Context, arg UpdateOrderPaymentInfoParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderPaymentInfo,
		arg.ID,
		arg.PaymentMethod,
		arg.MercadoPagoPaymentID,
		arg.TransactionDate,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.ParticipantID,
		&i.EventID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.MercadoPagoPaymentID,
		&i.MercadoPagoPreferenceID,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, registration_id, participant_id, event_id, amount, currency, status, payment_method, mercado_pago_payment_id, mercado_pago_preference_id, transaction_date, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID   `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.ParticipantID,
		&i.EventID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.MercadoPagoPaymentID,
		&i.MercadoPagoPreferenceID,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizer = `-- name: UpdateOrganizer :one
UPDATE organizers
SET
    business_name = $2,
    brand_name = $3,
    billing_zip_code = $4,
    billing_state = $5,
    billing_city = $6,
    contact_name = $7,
    contact_email = $8,
    contact_phone = $9,
    logo_url = $10,
    updated_at = NOW()
WHERE id = $1
RETURNING id, business_name, brand_name, rfc, billing_zip_code, billing_state, billing_city, contact_name, contact_email, contact_phone, logo_url, is_active, last_login, created_at, updated_at
`

type UpdateOrganizerParams struct {
	ID             uuid.UUID   `json:"id"`
	BusinessName   string      `json:"business_name"`
	BrandName      pgtype.Text `json:"brand_name"`
	BillingZipCode string      `json:"billing_zip_code"`
	BillingState   string      `json:"billing_state"`
	BillingCity    string      `json:"billing_city"`
	ContactName    string      `json:"contact_name"`
	ContactEmail   string      `json:"contact_email"`
	ContactPhone   string      `json:"contact_phone"`
	LogoUrl        pgtype.Text `json:"logo_url"`
}

func (q *Queries) UpdateOrganizer(ctx context.Context, arg UpdateOrganizerParams) (Organizer, error) {
	row := q.db.QueryRow(ctx, updateOrganizer,
		arg.ID,
		arg.BusinessName,
		arg.BrandName,
		arg.BillingZipCode,
		arg.BillingState,
		arg.BillingCity,
		arg.ContactName,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.LogoUrl,
	)
	var i Organizer
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.BrandName,
		&i.Rfc,
		&i.BillingZipCode,
		&i.BillingState,
		&i.BillingCity,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.LogoUrl,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateParticipant = `-- name: UpdateParticipant :one
UPDATE participants
SET
    first_name = $2,
    last_name = $3,
    second_last_name = $4,
    gender = $5,
    birth_date = $6,
    email = $7,
    phone = $8,
    country = $9,
    municipality = $10,
    state = $11,
    zip_code = $12,
    team = $13,
    size = $14,
    emergency_contact_name = $15,
    emergency_contact_phone = $16,
    medical_info = $17,
    waiver_signed_at = $18,
    updated_at = NOW()
WHERE id = $1
RETURNING id, first_name, last_name, second_last_name, gender, birth_date, email, phone, country, municipality, state, zip_code, team, size, emergency_contact_name, emergency_contact_phone, medical_info, waiver_signed_at, created_at, updated_at
`

type UpdateParticipantParams struct {
	ID                    uuid.UUID          `json:"id"`
	FirstName             string             `json:"first_name"`
	LastName              string             `json:"last_name"`
	SecondLastName        pgtype.Text        `json:"second_last_name"`
	Gender                string             `json:"gender"`
	BirthDate             time.Time          `json:"birth_date"`
	Email                 string             `json:"email"`
	Phone                 string             `json:"phone"`
	Country               string             `json:"country"`
	Municipality          pgtype.Text        `json:"municipality"`
	State                 pgtype.Text        `json:"state"`
	ZipCode               pgtype.Text        `json:"zip_code"`
	Team                  pgtype.Text        `json:"team"`
	Size                  pgtype.Text        `json:"size"`
	EmergencyContactName  pgtype.Text        `json:"emergency_contact_name"`
	EmergencyContactPhone pgtype.Text        `json:"emergency_contact_phone"`
	MedicalInfo           pgtype.Text        `json:"medical_info"`
	WaiverSignedAt        pgtype.Timestamptz `json:"waiver_signed_at"`
}

func (q *Queries) UpdateParticipant(ctx context.Context, arg UpdateParticipantParams) (Participant, error) {
	row := q.db.QueryRow(ctx, updateParticipant,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.SecondLastName,
		arg.Gender,
		arg.BirthDate,
		arg.Email,
		arg.Phone,
		arg.Country,
		arg.Municipality,
		arg.State,
		arg.ZipCode,
		arg.Team,
		arg.Size,
		arg.EmergencyContactName,
		arg.EmergencyContactPhone,
		arg.MedicalInfo,
		arg.WaiverSignedAt,
	)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.SecondLastName,
		&i.Gender,
		&i.BirthDate,
		&i.Email,
		&i.Phone,
		&i.Country,
		&i.Municipality,
		&i.State,
		&i.ZipCode,
		&i.Team,
		&i.Size,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.MedicalInfo,
		&i.WaiverSignedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePricingStage = `-- name: UpdatePricingStage :one
UPDATE pricing_stages
SET name = $2, price = $3, start_date = $4, end_date = $5, is_early_bird = $6
WHERE id = $1
RETURNING id, distance_id, name, price, start_date, end_date, is_early_bird, created_at
`

type UpdatePricingStageParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        pgtype.Text    `json:"name"`
	Price       pgtype.Numeric `json:"price"`
	StartDate   time.Time      `json:"start_date"`
	EndDate     time.Time      `json:"end_date"`
	IsEarlyBird pgtype.Bool    `json:"is_early_bird"`
}

func (q *Queries) UpdatePricingStage(ctx context.Context, arg UpdatePricingStageParams) (PricingStage, error) {
	row := q.db.QueryRow(ctx, updatePricingStage,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.StartDate,
		arg.EndDate,
		arg.IsEarlyBird,
	)
	var i PricingStage
	err := row.Scan(
		&i.ID,
		&i.DistanceID,
		&i.Name,
		&i.Price,
		&i.StartDate,
		&i.EndDate,
		&i.IsEarlyBird,
		&i.CreatedAt,
	)
	return i, err
}

const updateRegistrationCheckIn = `-- name: UpdateRegistrationCheckIn :one
UPDATE registrations
SET checked_in_at = NOW()
WHERE id = $1
RETURNING id, event_id, participant_id, distance_id, category, bib_number, qr_code, time, status, registration_date, checked_in_at
`

func (q *Queries) UpdateRegistrationCheckIn(ctx context.Context, id uuid.UUID) (Registration, error) {
	row := q.db.QueryRow(ctx, updateRegistrationCheckIn, id)
	var i Registration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ParticipantID,
		&i.DistanceID,
		&i.Category,
		&i.BibNumber,
		&i.QrCode,
		&i.Time,
		&i.Status,
		&i.RegistrationDate,
		&i.CheckedInAt,
	)
	return i, err
}

const updateRegistrationLocation = `-- name: UpdateRegistrationLocation :one
UPDATE registration_locations
SET location_name = $2, address = $3, schedule = $4
WHERE id = $1
RETURNING id, event_id, location_name, address, schedule, created_at
`

type UpdateRegistrationLocationParams struct {
	ID           uuid.UUID   `json:"id"`
	LocationName string      `json:"location_name"`
	Address      string      `json:"address"`
	Schedule     pgtype.Text `json:"schedule"`
}

func (q *Queries) UpdateRegistrationLocation(ctx context.Context, arg UpdateRegistrationLocationParams) (RegistrationLocation, error) {
	row := q.db.QueryRow(ctx, updateRegistrationLocation,
		arg.ID,
		arg.LocationName,
		arg.Address,
		arg.Schedule,
	)
	var i RegistrationLocation
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.LocationName,
		&i.Address,
		&i.Schedule,
		&i.CreatedAt,
	)
	return i, err
}

const updateRegistrationQRCode = `-- name: UpdateRegistrationQRCode :one
UPDATE registrations
SET qr_code = $2
WHERE id = $1
RETURNING id, event_id, participant_id, distance_id, category, bib_number, qr_code, time, status, registration_date, checked_in_at
`

type UpdateRegistrationQRCodeParams struct {
	ID     uuid.UUID   `json:"id"`
	QrCode pgtype.Text `json:"qr_code"`
}

func (q *Queries) UpdateRegistrationQRCode(ctx context.Context, arg UpdateRegistrationQRCodeParams) (Registration, error) {
	row := q.db.QueryRow(ctx, updateRegistrationQRCode, arg.ID, arg.QrCode)
	var i Registration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ParticipantID,
		&i.DistanceID,
		&i.Category,
		&i.BibNumber,
		&i.QrCode,
		&i.Time,
		&i.Status,
		&i.RegistrationDate,
		&i.CheckedInAt,
	)
	return i, err
}

const updateRegistrationStatus = `-- name: UpdateRegistrationStatus :one
UPDATE registrations
SET status = $2
WHERE id = $1
RETURNING id, event_id, participant_id, distance_id, category, bib_number, qr_code, time, status, registration_date, checked_in_at
`

type UpdateRegistrationStatusParams struct {
	ID     uuid.UUID   `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateRegistrationStatus(ctx context.Context, arg UpdateRegistrationStatusParams) (Registration, error) {
	row := q.db.QueryRow(ctx, updateRegistrationStatus, arg.ID, arg.Status)
	var i Registration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ParticipantID,
		&i.DistanceID,
		&i.Category,
		&i.BibNumber,
		&i.QrCode,
		&i.Time,
		&i.Status,
		&i.RegistrationDate,
		&i.CheckedInAt,
	)
	return i, err
}

const updateRunnerKitItem = `-- name: UpdateRunnerKitItem :one
UPDATE runner_kit_items SET name = $2, icon = $3 WHERE id = $1 RETURNING id, event_id, name, icon, created_at
`

type UpdateRunnerKitItemParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Icon        string    `json:"icon"`
}

func (q *Queries) UpdateRunnerKitItem(ctx context.Context, arg UpdateRunnerKitItemParams) (RunnerKitItem, error) {
	row := q.db.QueryRow(ctx, updateRunnerKitItem,
		arg.ID,
		arg.Name,
		arg.Icon,
	)
	var i RunnerKitItem
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
	)
	return i, err
}

const updateSponsor = `-- name: UpdateSponsor :one
UPDATE sponsors
SET name = $2, tier = $3, logo_url = $4, website_url = $5
WHERE id = $1
RETURNING id, event_id, name, tier, logo_url, website_url, created_at
`

type UpdateSponsorParams struct {
	ID         uuid.UUID   `json:"id"`
	Name       string      `json:"name"`
	Tier       string      `json:"tier"`
	LogoUrl    pgtype.Text `json:"logo_url"`
	WebsiteUrl pgtype.Text `json:"website_url"`
}

func (q *Queries) UpdateSponsor(ctx context.Context, arg UpdateSponsorParams) (Sponsor, error) {
	row := q.db.QueryRow(ctx, updateSponsor,
		arg.ID,
		arg.Name,
		arg.Tier,
		arg.LogoUrl,
		arg.WebsiteUrl,
	)
	var i Sponsor
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Tier,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserActive = `-- name: UpdateUserActive :one
UPDATE users
SET is_active = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, role, organizer_id, participant_id, is_active, last_login, created_at, updated_at
`

type UpdateUserActiveParams struct {
	ID       uuid.UUID   `json:"id"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserActive, arg.ID, arg.IsActive)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.OrganizerID,
		&i.ParticipantID,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :one
UPDATE users
SET last_login = NOW()
WHERE id = $1
RETURNING id, email, password_hash, role, organizer_id, participant_id, is_active, last_login, created_at, updated_at
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, updateUserLastLogin, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.OrganizerID,
		&i.ParticipantID,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, role, organizer_id, participant_id, is_active, last_login, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.OrganizerID,
		&i.ParticipantID,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEventFieldConfig = `-- name: UpsertEventFieldConfig :one
INSERT INTO event_field_config (
    event_id, section_name, is_enabled, is_required
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (event_id, section_name)
DO UPDATE SET
    is_enabled = $3,
    is_required = $4,
    updated_at = NOW()
RETURNING id, event_id, section_name, is_enabled, is_required, created_at, updated_at
`

type UpsertEventFieldConfigParams struct {
	EventID     uuid.UUID `json:"event_id"`
	SectionName string    `json:"section_name"`
	IsEnabled   bool      `json:"is_enabled"`
	IsRequired  bool      `json:"is_required"`
}

func (q *Queries) UpsertEventFieldConfig(ctx context.Context, arg UpsertEventFieldConfigParams) (EventFieldConfig, error) {
	row := q.db.QueryRow(ctx, upsertEventFieldConfig,
		arg.EventID,
		arg.SectionName,
		arg.IsEnabled,
		arg.IsRequired,
	)
	var i EventFieldConfig
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.SectionName,
		&i.IsEnabled,
		&i.IsRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEventParticipantField = `-- name: UpsertEventParticipantField :one
INSERT INTO event_participant_fields (
    event_id, field_name, is_required, is_enabled, display_order
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (event_id, field_name)
DO UPDATE SET
    is_required = $3,
    is_enabled = $4,
    display_order = $5
RETURNING id, event_id, field_name, is_required, is_enabled, display_order, created_at
`

type UpsertEventParticipantFieldParams struct {
	EventID      uuid.UUID   `json:"event_id"`
	FieldName    string      `json:"field_name"`
	IsRequired   bool        `json:"is_required"`
	IsEnabled    bool        `json:"is_enabled"`
	DisplayOrder pgtype.Int4 `json:"display_order"`
}

func (q *Queries) UpsertEventParticipantField(ctx context.Context, arg UpsertEventParticipantFieldParams) (EventParticipantField, error) {
	row := q.db.QueryRow(ctx, upsertEventParticipantField,
		arg.EventID,
		arg.FieldName,
		arg.IsRequired,
		arg.IsEnabled,
		arg.DisplayOrder,
	)
	var i EventParticipantField
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.FieldName,
		&i.IsRequired,
		&i.IsEnabled,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}
